baseURL = 'http://hugo-quickstart-template.netlify.com'
languageCode = 'en-us'
title = 'Netlify + Hugo Quickstart'
theme = 'netlify-basic'
ignoreFiles = ["^/content/categories/.*$", "^/content/labels/.*$"]# excluding my category and label pages for the build
